yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  styled-components@*:
    dependencies:
      react-is: "*"
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
